language: go
go:
  - 1.8
  - 1.7

services:
  - postgresql

before_script:
  - psql -c "create database sqlrow_test;" -U postgres
  - psql -c "create user sqlrow_test with password 'sqlrow_test';" -U postgres
  - psql -c "grant all privileges on database sqlrow_test to sqlrow_test;" -U postgres

install:
  - go get github.com/jjeffery/errors
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3
  - go get gopkg.in/DATA-DOG/go-sqlmock.v1
  - go get github.com/spf13/pflag
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test . ./private/...
  - go test -race
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
