language: go
go:
  - 1.8
  - 1.7

services:
  - postgresql

before_script:
  - psql -c "create database sqlr_test;" -U postgres
  - psql -c "create user sqlr_test with password 'sqlr_test';" -U postgres
  - psql -c "grant all privileges on database sqlr_test to sqlr_test;" -U postgres

install:
  - go get github.com/jjeffery/errors
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3
  - go get gopkg.in/DATA-DOG/go-sqlmock.v1

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

